GET http://localhost:3001/exercices/

###
GET http://localhost:3001/exercices/1

###
POST http://localhost:3001/exercices/
Content-Type: application/json

{
  "name": "Bras",
  "description": "Lorem Ipsum",
  "difficulty": "Medium",
  "time": "30 min",
  "repetitions": "4 x 15",
  "createdAt": "maintenant",
  "categoryId": 2
}

### 
PUT http://localhost:3001/exercices/3
Content-Type: application/json

{
  "name": "Abdos",
  "description": "Lorem Ipsum",
  "difficulty": "Easy",
  "time": "20 min",
  "repetitions": "4 x 15",
  "createdAt": "maintenant",
  "categoryId": 3
}