GET http://localhost:3001/users/

###

POST http://localhost:3001/users/
Content-Type: application/json

{
  "firstname": "Aude",
  "lastname": "Sedillo",
  "email": "celia@gmail.com",
  "password": "toto",
  "picture": "https://png.pngtree.com/png-vector/20220817/ourmid/pngtree-man-avatar-with-circle-frame-vector-ilustration-png-image_6110328.png",
  "exercicesId": "[4, 11]",
  "role": ["client"]
}

###

POST http://localhost:3001/users/login
Content-Type: application/json

{
  "email": "celia@gmail.com",
  "password": "toto",
  "role": "[CLIENT]"
}